export const LLMOS = {
  DASHBOARD: 'dashboard',
  SETTING:   'management.llmos.ai.setting',
  MODELFILE: 'management.llmos.ai.setting',
  CHAT:      'chat',
  // CLUSTER:         'management.cluster.ai.setting',
  // ML_CLUSTER:      'ray.io.raycluster',
  // NOTEBOOK:        'ml.llmos.ai.notebook',
  // ADD_ONS:         'k3s.cattle.io.addon',
  // NODE:            'node',
  // NODE_NETWORK:    'network.harvesterhci.io.nodenetwork',
  // CLUSTER_NETWORK: 'network.harvesterhci.io.clusternetwork',
  // QUEUE:           'scheduling.volcano.sh.queue',
  // NAMESPACE:       'namespace',
};
